# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4957a16c4d6ffa44b5130d9876ae01ac39c389edff8b5d8d54abfe1243fd9bdb7b727f3f8e227101f27c177433487ca56bc496100e36a39f582cd3068a470dea

test:
  secret_key_base: aec0fdd214548de977c2f776827bdfb740b726ac165d0d6b9bc928dea45c31051ce9cc4fdbd051a6e43f628bf93f7d0c527b1d9e851fb13875913507fc7b8252

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
